config/routes.rb
Rails.application.routes.draw do
  resources :blogs do
    collection do
      post :confirm
    end
  end
  resources :users, only: [:new, :create, :show]
  resources :sessions, only: [:new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user
  validates :title, presence: true

  mount_uploader :image, ImageUploader

end

app/models/user.rb
class User < ApplicationRecord
    validates :name,presence: true, length: { maximum:30 }
    validates :email,presence: true, length: { maximum:255 }
    validates :email,format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
    before_validation { email.downcase! }
    has_secure_password
    validates :password, length: { minimum: 6 }

    has_many :blogs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    include SessionsHelper
    before_action :login_required

    private

    def login_required
        redirect_to new_session_path unless current_user
    end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  def index
    @blogs = Blog.all
  end

  def new
    @blog = Blog.new
  end

  def create
    @blog = current_user.blogs.build(blog_params)
    if params[:back]
      render :new
    else
      if @blog.save
      redirect_to blogs_path, notice: "ブログ作成しました！"
      else
        render :new
      end
    end    
  end

  def show
    @blog = Blog.find(params[:id])
  end

  def edit
    @blog = Blog.find(params[:id])
  end

  def update
    @blog = Blog.find(params[:id])
    if @blog.update(blog_params)
      redirect_to blogs_path, notice: "ブログを編集しました！！"
    else
      render :edit
    end
  end

  def destroy
  @blog = Blog.find(params[:id])
  @blog.destroy
  redirect_to blogs_path, notice:"ブログを削除しました！"
  end

  def confirm
    @blog = current_user.blogs.build(blog_params)
    render :new if @blog.invalid?
  end

  private

  def blog_params
    params.require(:blog).permit(:title, :content,:image, :image_cache)
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]


  def new
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    skip_before_action :login_required, only: [:new, :create]

    def new
        @user = User.new
    end

    def show
        @user = User.find(params[:id])
    end

    def create
        @user = User.new(user_params)
        if @user.save
            redirect_to user_path(@user.id)
        else
            render :new
        end
    end


    private

    def user_params
        params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
    def choose_new_or_edit
        if action_name == 'new' || action_name == 'create'
            confirm_blogs_path
        elsif action_name == 'edit'
            blog_path
        end
    end
end

app/helpers/sessions_helper.rb
module SessionsHelper
    
    def current_user
    @current_user ||= User.find_by(id: session[:user_id])
    end

    def logged_in?
        current_user.present?
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/confirm.html.erb
<h3>以下の内容で、送信する。</h3>

<%= form_with(model: @blog, url: blogs_path, local: true ) do |form| %>

<%= image_tag(@blog.image.url) if @blog.image && @blog.image.url %>

   <%= form.hidden_field :title %>
   <%= form.hidden_field :content %>
   <%= form.hidden_field :image_cache %>

   <p>タイトル: <%= @blog.title %></p>
   <p>内容: <%= @blog.content %></p>
   <%= form.submit "登録する" %>

   <%= form.submit '戻る', name: 'back' %>
<% end %>

app/views/blogs/edit.html.erb
<%= form_with(model: @blog, local: true) do |form| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= @blog.errors.count %>件のエラーがあります。</h2>
      <ul>

        <% @blog.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
   <% end %>

  <div class="blog_field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>
  <div class="blog_title">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div class="blog_content">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>
  <%= form.submit %>
  <%= form.submit '戻る', name: 'back' %>
  
<% end %>

app/views/blogs/index.html.erb
<h1>ブログ一覧</h1>

<p><%= notice %></p>

<table>
    <tr>
      <th>タイトル</th>
      <th>内容</th>
    </tr>

<% @blogs.each do |blog| %>
    <tr>
        <td><%= blog.title %></td>
        <td><%= blog.content %></td>
        
        <td><%= link_to '詳細を確認する', blog_path(blog.id) %></td>
        <td><%= link_to "ブログを編集する", edit_blog_path(blog.id), data: { confirm: '本当に編集していいですか？？'} %></td>
        <td><%= link_to 'ブログを削除する', blog_path(blog.id), method: :delete ,data: { confirm: '本当に削除しますよ？？'}%></td>
            
    </tr>
<% end %>
</table>

<%= link_to '新しくブログを投稿する',new_blog_path %>

app/views/blogs/new.html.erb
<h2>ブログを作成する</h2>
<%= render 'form' %>

<%= form_with(model: @blog, local: true,url: {action: 'confirm'}) do |form| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= @blog.errors.count %>件のエラーがあります。</h2>
      <ul>

        <% @blog.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
   <% end %>

  <div class="blog_field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>
  <div class="blog_title">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div class="blog_content">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>
  <%= form.submit %>
<% end %>

<%= link_to "ブログ一覧画面にもどる", blogs_path %>

app/views/blogs/show.html.erb
<h1>ブログ詳細画面</h1>
<P>タイトル: <%= @blog.title %></p>
<p>内容: <%= @blog.content %></p>
<p>画像: <%= image_tag @blog.image.url %>


<%= link_to "ブログ一覧画面にもどる", blogs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FriendsAppExam</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header>
        <ul class="header-logo" >
          <li>
            <%= image_tag 'image1.png', :size => '300x150'%>
          </li>
        </ul>
  </header>
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>

    <% if logged_in? %>
      <%= link_to "Profile", user_path(current_user.id) %>
      <%= link_to "Logout", session_path(current_user.id), method: :delete %>
    <% else %>
      <%= link_to "Sign up", new_user_path %>
      <%= link_to "Login", new_session_path %>
    <% end %>
    
    <%= yield %>
    
      <footer>
        <ul class="footer-logo" >
          <li>
            友達繋がりアプリケーション　課題
          </li>
        </ul>
      </footer>
  </body>
</html>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<% if @user.errors.any? %>
 <div id="error_explanation">
  <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
  <ul>
  <% @user.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
  </ul>
  </div>
<% end %>

<%= form_with(model: @user,local:true) do |f| %>
 <%= f.label :name %>
 <%= f.text_field :name %>

 <%= f.label :email %>
 <%= f.email_field :email %>

 <%= f.label :password %>
 <%= f.password_field :password %>

 <%= f.label :password_confirmation %>
 <%= f.password_field :password_confirmation %>

 <%= f.submit "Create my account" %>

 <% end %>

app/views/users/show.html.erb
<h1><%= @user.name %>のページ</h1>

<p>メールアドレス: <%= @user.email %></p>

<%= link_to '新しくブログを投稿する',new_blog_path %>
<br>
<%= link_to '投稿一覧へ',blogs_path %>